server:
  port: 8090
spring:
  redis:
    database: 0
    host: 101.37.173.73
    port: 6379
    password: PCY90321
    timeout: 5000
    # 连接耗尽时是否阻塞, false报异常,true阻塞直到超时, 默认true
    block-when-exhausted: true
    jedis:
      pool:
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 100
        # 连接池中的最大空闲连接
        max-idle: 10
        # 连接池中的最小空闲连接
        min-idle: 2
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: 10000